---
abstract: 'Adds syntactic sugar to skip the fancy objects'
author:
  - 'Johannes Plunien <plu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-ResultSet-HashRef
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.002
