---
abstract: 'Adds syntatic sugar to skip the fancy objects'
author:
  - 'Johannes Plunien <plu@cpan.org>'
build_requires:
  File::Temp: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-ResultSet-HashRef
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  perl: 5.6.1
version: 1.000
